parameters:
    mu_core_doctrine_dbal_url: '%env(resolve:MU_DATABASE_URL)%'
    mu_core_elasticsearch_url: '%env(resolve:MU_ELASTICSEARCH_URL)%'
    mu_core_dir: '%kernel.project_dir%/vendor/megaubytovanie/mu-core-bundle'